### ISSUE TITLE
Legacy template needs to extend `generic/object_list.html`

### ISSUE THREAD

**Issue by HanlinMiao** [nautobot/nautobot-plugin-device-onboarding#66] opened 2022-12-27 20:49 UTC
https://github.com/nautobot/nautobot-plugin-device-onboarding/blob/develop/nautobot_device_onboarding/templates/nautobot_device_onboarding/onboarding_tasks_list.html
needs to be changed to extend `generic/object_list.html`

**Comment by glennmatthews** [comment] 2023-01-23 21:58
duplicate of #63, fixed by #65.

**Closed by glennmatthews** 2023-01-23 21:58 UTC
Labels: type: housekeeping
